settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: src
  path: .
  commands:
    install:
      status: true
      method: go build -o /go/bin/api ./server.go
    run:
      status: true
      method: /go/bin/api
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
