settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 1999
  host: '0.0.0.0'
schema:
- name: src
  path: .
  commands: {}
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
