version: '3.4'

services:
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: dev
    container_name: goapi
    stdin_open: true
    tty: true
    ports:
      - 1999:1999
    # volumes:
    #   - ./:/go/src
