version: '3.5'

services:
  app:
    build:
      context: .
      target: build
    container_name: goapi
    volumes:
      - ./:/go/src/app
    command: realize start --run --no-config
    ports:
      - 1999:1999 # for WebServer