version: '3.4'

services:
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: dev
    container_name: goapi
    environment: 
      HOST: 0.0.0.0
      PORT: '1999'
    volumes:
      - ./:/go/src
    stdin_open: true
    tty: true
    ports:
      - 1999:1999
