version: '3'

services:
  app:
    build: ./src/app
    container_name: goapi
    working_dir: /go/src/app
    volumes:
        - ./src:/go/src
    command: go run server.go
    ports:
      - 1999:1999