version: '3.4'
services:

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      target: builder
    container_name: goapi
    command: ["/app/api"]
    ports:
      - 1999:1999
    networks:
      - go_api

networks:
  go_api:
    external: true
